##
# Container to build microperl
FROM ubuntu
MAINTAINER Alexei KLENIN <alexei.klenin@gmail.com>

ENV PERL_VERSION 5.23.4

VOLUME /export      # built binaries

# Move to directory with sources
WORKDIR /perl-src

# Install build-essential
RUN apt-get update \
    && apt-get install -y build-essential

# Download sources of Perl
ADD http://www.cpan.org/src/5.0/perl-$PERL_VERSION.tar.gz /

# Extract sources
RUN tar -xzf /perl-$PERL_VERSION.tar.gz -C /perl-src --strip-components=1

# Make config
RUN make -f Makefile.micro regen_uconfig64 \
    && make -f Makefile.micro patch_uconfig

# Apply patches
COPY patch /perl-src/

# Build microperl from sources
RUN make -f Makefile.micro

# Export build binary
CMD cp microperl /export/
